#!/bin/bash

# This project is licensed under the MIT License (see LICENSE).

set -eu

readonly CONFIG="${AUTO_INHIBIT_CONF:-/etc/auto-inhibit.conf}"
readonly COMMAND="${AUTO_INHIBIT_CMD:-systemd-inhibit}"
readonly INHIBITOR="${AUTO_INHIBITOR:-$(command -v auto-inhibit)}"

check_config() {
    if [[ ! -e "$CONFIG" ]]; then
        echo "$CONFIG does not exist" >&2
        exit 1
    fi
}

is_inhibitor_link() {
    [[ -L "$1" && "$(readlink -f "$1")" == "$INHIBITOR" ]]
}

name="$(basename "$0")"

if [[ "$name" != 'auto-inhibit' ]]; then
    check_config

    path=''

    for p in $(type -a "$name" 2> /dev/null | awk '{print $NF}'); do
        case "$p" in
            builtin|keyword)
                err="$p"
                continue
        esac
        if ! is_inhibitor_link "$p"; then
            path="$p"
            break
        fi
    done

    if [[ -z "$path" ]]; then
        msg='not found'
        [[ -n "${err-}" ]] && msg="is a shell $err"
        echo "$name $msg" >&2
        exit 1
    fi

    mapfile -t flags < <(iniq -p "$name" -f '--%k=%v' "$CONFIG")

    exec "$COMMAND" "${flags[@]}" "$path" "$@"
fi

symdir='/usr/local/bin'

declare -a links=()

usage() {
    echo 'usage: auto-inhibit [options] [command]

options:
  -h        Show help message
  -d DIR    Operate on DIR

commands:
  list      List symlinks
  generate  Create symlinks
  check     Check symlinks
  remove    Remove symlinks
  status    List active inhibitors'
}

get_links() {
    for f in "$symdir"/*; do
        is_inhibitor_link "$f" && links+=("$f")
    done
    return 0
}

status() {
    systemd-inhibit --list
    exit $?
}

while getopts ':hd:' opt; do
    case "$opt" in
        h) usage; exit ;;
        d) symdir="$OPTARG" ;;
        *) usage >&2; exit 2
    esac
done

shift $((OPTIND - 1))

[[ $# -eq 0 ]] && status

case "$1" in
    list)
        get_links
        for f in "${links[@]}"; do
            echo "${f##*/}"
        done
        ;;
    generate)
        check_config
        for f in $(iniq -d "$CONFIG"); do
            ln -vs "$INHIBITOR" "$symdir/$f"
        done
        ;;
    check)
        check_config
        r=0
        for f in $(iniq -d "$CONFIG"); do
            err=''
            if [[ ! -e "$symdir/$f" ]]; then
                err="$f does not exist"
            elif ! is_inhibitor_link "$symdir/$f"; then
                err="$f is not a symlink to auto-inhibit"
            fi
            if [[ -n "$err" ]]; then
                echo "$err" >&2
                (( r+=1 ))
            fi
        done
        exit $r
        ;;
    remove)
        get_links
        for f in "${links[@]}"; do
            rm -v "$f"
        done
        ;;
    status) status ;;
    *) usage >&2; exit 2
esac
